version: '3'

services:
  allure:
    image: "frankescobar/allure-docker-service:latest"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - C:/Users/user/allure-docker-python-pytest-example\allure-results:/app/allure-results
      - C:/Users/user/allure-docker-python-pytest-example\allure-reports:/app/allure-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui:latest"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
